cell.png:
	magick xc:transparent -geometry 300x300 \
	-fill burlywood3 -stroke black -strokewidth 2 -draw "roundrectangle 20,20,280,280,20,20" \
	-fill burlywood1 -stroke black -strokewidth 2 -draw "roundrectangle 30,30,270,270,20,20" $@
